### ISSUE TITLE
Bug in delete deployment preview

### ISSUE THREAD

**Issue by sakethsomaraju** [astronomer/deploy-action#102]
While creating `create-deployment-preview` , `/` are being striped off, even if the actual branch name consists `/`

```
 if [[ ${GITHUB_HEAD_REF##*/} != "" ]]; then
              BRANCH_DEPLOYMENT_NAME=${GITHUB_HEAD_REF##*/}_$DEPLOYMENT_NAME
 else
              branch_ref="${{ github.ref }}"
              branch_name="${branch_ref##*/}"
              BRANCH_DEPLOYMENT_NAME=${branch_name}_$DEPLOYMENT_NAME
  fi
```
This causes issues with deletion  `delete-deployment-preview` as no cleanup is performed [below](https://github.com/astronomer/deploy-action/blob/f81e5461d71f8c88700d70531267fb59f84e96b5/action.yaml#L248).

```
BRANCH_DEPLOYMENT_NAME=${{ github.event.ref }}_$DEPLOYMENT_NAME
```

**Steps to reproduce:**

1. Use the following step to create a preview deployment with branch name `feature/test-br`
```
 - name: Deploy to Astro DAGS
      id: deploy_to_astro
      continue-on-error: true
      # if: ${{ github.event.inputs.deploy_type == 'DAGS' }}
      uses: astronomer/deploy-action@v0.8.0
      with:
        action: create-deployment-preview
        deployment-id: ${{ env.DEPLOYMENT_ID }}
```
2. commit the following workflow to main branch.
```
name: Personal Astronomer CI - Deploy
# on:
#   push:
#     branches:
#       - main

on:
  delete:
    branches:
      - "**"
  workflow_dispatch:

env:
  ## Sets Deployment API credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  WORKSPACE: "clilt7vco00a601kk5fz65ob1"  
  DEPLOYMENT_ID: "cm4kns26b04ig01inliml8o7x" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Delete preview deployment
      uses: astronomer/deploy-action@v0.8.0
      with:
        action: delete-deployment-preview
        deployment-id: cm4mdzw2g0fwi01lgxxx2zyy7

 
```
3. Delete `feature/test-br` on remote to trigger workflow with `git push origin -d feature/test-br`
4. Workflow fails with ` No Deployment with the name feature/test-br_test was found` 

But it should try to delete `test-br_test`
