### ISSUE TITLE
Unable to deploy dags in v0.9.0

### ISSUE THREAD

**Issue by nsivapra** [astronomer/deploy-action#103]
I've recently upgraded the deploy actions from `astronomer/deploy-action@v0.4.0` to `astronomer/deploy-action@v0.9.0` to use `wake-on-deploy`. However, I'm noticing none of the dag deploys and updates are appearing in the instance.

Github actions:

```
    - name: Deploy to ephemeral instance
      uses: astronomer/deploy-action@v0.9.0
      with:
        preview-name: '${{ github.event.pull_request.head.ref }}-ephemeral'
        root-folder: ./astro
        action: deploy-deployment-preview
        force: true
        checkout: false
        deployment-id: [deployment_id]
        wake-on-deploy: true
``` 

File update in actions:

- 1 file is updated
<img width="548" alt="Image" src="https://github.com/user-attachments/assets/06f8f39e-841e-491d-84cd-cda64c1c5893" />

Astro instance:

- No updates for this dag update
<img width="706" alt="Image" src="https://github.com/user-attachments/assets/009dd20c-bb10-4bf6-b56f-f9792656ebc9" />

Am I missing anything in setting up this action?
