### ISSUE TITLE
Create deployment preview should have exist_ok option

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/deploy-action#107]
The currently recommended workflow of creating a deployment preview on branch creation is not good for my use case. We often create branches that are not ready for any kind of testing and do not need a preview created. I would like to use on: pull-request, but this means that the creation step often fails as I'm updating the PR, because the preview only needs to be created once. I'm using `if: always()` on the deploy step as a workaround, but it'd be better if I had a flag to allow create-preview to be idempotent.

```
name: Astronomer CI - preview Deployment

on:
  pull_request:
    branches:
      - main

env:
  ASTRO_API_TOKEN: ${{ secrets.XXXX }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.9.0
      with:
        action: create-deployment-preview
        deployment-id: clxxxx
        root-folder: ./airflow
    - name: Deploy code to preview
      if: '!cancelled()'
      uses: astronomer/deploy-action@v0.9.0
      with:
        action: deploy-deployment-preview
        deployment-id: clxxxx
        root-folder: ./airflow
```

**Comment by collinmcnulty** [comment]
I was able to work around this by adding continue-on-error: true

```
name: Astronomer CI - preview Deployment

on:
  pull_request:
    branches:
      - main

env:
  ASTRO_API_TOKEN: ${{ secrets.XXXX }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.9.0
      continue-on-error: true
      with:
        action: create-deployment-preview
        deployment-id: clxxxx
        root-folder: ./airflow
    - name: Deploy code to preview
      if: '!cancelled()'
      uses: astronomer/deploy-action@v0.9.0
      with:
        action: deploy-deployment-preview
        deployment-id: clxxxx
        root-folder: ./airflow
```
