### ISSUE TITLE
mount-path parameter for dbt deploys not functioning properly

### ISSUE THREAD

**Issue by caitlin-petro** [astronomer/deploy-action#118]
I am facing an issue when using the dbt deploy via GitHub Actions template with a custom mount-path.  It seems that the action is not utilizing the custom mount-path at all.

Template Example:
```
name: Astronomer CI - Deploy DAG and dbt code to Astro

on: 
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variable
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: DBT Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm60u64ec0lj801ns7rsvuj29
        deploy-type: dbt
        root-folder: dbt/dbtproject/
        mount-path: /usr/local/airflow/dbt/mytest/blahblah
    - name: DAGs/Image Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm60u64ec0lj801ns7rsvuj29
        root-folder: astro-project/
        force: true
```

Action Triggered: https://github.com/caitlin-petro/dbt-demo-2/actions/runs/14503956724/job/40689726721

Log Outputs:

It registers that I've input the custom mount-path
`2025-04-16T22:39:39.8998539Z   mount-path: /usr/local/airflow/dbt/mytest/blahblah`
Twice...
```2025-04-16T22:39:41.8191833Z [36;1m  # Add mount path option[0m
2025-04-16T22:39:41.8192147Z [36;1m  if [[ "/usr/local/airflow/dbt/mytest/blahblah" != "" ]]; then[0m
2025-04-16T22:39:41.8192582Z [36;1m    options="$options --mount-path=/usr/local/airflow/dbt/mytest/blahblah"[0m
2025-04-16T22:39:41.8192920Z [36;1m  fi[0m
```

Then disregards it and generates the default mount-path
`2025-04-16T22:39:42.1251031Z Generated mount path from dbt project name: /usr/local/airflow/dbt/dbtproject`
And does a dbt deploy with the default mount-path
`2025-04-16T22:39:41.9933595Z [36;1m astro dbt deploy <my_deployment_id>`

Deploying the dbt deploy locally using the --mount-path flag works perfectly fine and mounts it in the custom path as expected:
`astro dbt deploy <my_deployment_id> --mount-path="/usr/local/airflow/dbt/mytest/blahblah"`
