### ISSUE TITLE
v0.6 fails to deploy due to issue with git diff command

### ISSUE THREAD

**Issue by ryanherring** [astronomer/deploy-action#69]
I'm finding that the v0.6 version of the deploy-action fails 100% of the time at the step where this [sub-command is run](https://github.com/astronomer/deploy-action/blob/0862e377d1907e1ab612382b988e48f81572bab6/action.yaml#L277):

```sh
files=$(git diff --name-only 43051cdd6f4318ca3509f9034ea15ab39e28d470 45dbf8198402634782255c694871f075b8a8b17c)
```

The two commit hashes above are both valid and that command runs fine from my local copy of the repo. The error message I get from the deploy-action is (redacted the name of our repo):

```sh
Branch pushed to: main
From https://github.com/****************
 * branch            main       -> FETCH_HEAD
fatal: bad object 43051cdd6f4318ca3509f9034ea15ab39e28d470
```

Which suggests that whatever state of the local git repo the deploy-action has, it is unable to see those commits (which are in `main`). The configuration I'm using is:

```yaml
    - uses: actions/checkout@v4

    - name: Write Git SHA to file
        run: |
          echo "${{ github.sha }}" > dags/utils/resources/git_commit_sha.txt

    - name: Deploy to Astronomer
        uses: astronomer/deploy-action@v0.6
        with:
          workspace: Main
          deployment-name: ${ASTRO_DEPLOYMENT_NAME}
          deploy-image: ${{ github.ref == 'refs/heads/as-prod' }}
          parse: true
          checkout: false
```

We are intentionally using `checkout: false` because we have our own checkout action further up the script where we had a custom file that we want the script to generate and then include in the files deployed to our Astronomer environment. We also want to use `deploy-image: true` whenever we are deploying to our production environment (which corresponds to our `as-prod` branch).

I wanted to ask if v0.6 of this action has been tested with the `checkout: false` option as it seems like it could be a possible reason for the failure I'm seeing (although I am far from certain about this).

**Comment by sunkickr** [comment]
I found that with previous latest version of the github action `v0.4` that setting `checkout: false` actually did not do anything. So in `v0.6` this is now fixed and we tested that it works now. See the release notes here: https://github.com/astronomer/deploy-action/releases.

You are saying that you have your own checkout script further up the script. You must run checkout before running `astronomer/deploy-action@v0.6`. It is required for the deploy action to run successfully. If not it does not have access to the git objects and you get the error shown. If you are running it after it will fail.

The checkout step must be running twice in the code you show above because setting `checkout: false` does not work in `v0.4` which is why it worked for you in `v0.4` and not in `v0.6`. Id either move you checkout step above the step were the deploy action runs or set `checkout: true`

**Comment by ryanherring** [comment]
@sunkickr - thanks for the reply. Here is a larger snippet of our YAML file (for use with v0.4). Perhaps adding in `actions/checkout@v4` further up fixed the issue we were seeing whereas we attributed it to adding `checkout: false`. We made both of those changes at the same time.

```yaml
      - uses: actions/checkout@v4

      - name: Write Git SHA to file
        run: |
          echo "${{ github.sha }}" > dags/utils/resources/git_commit_sha.txt

      - name: Deploy to Astronomer
        uses: astronomer/deploy-action@v0.4
        with:
          workspace: Main
          deployment-name: ${ASTRO_DEPLOYMENT_NAME}
          parse: true
          checkout: false
```

I also updated the original text of this issue to include more of the YAML file we are trying to merge plus more of the output of the action logs prior to failure. It's clear that the `deploy-action` script is able to run the `git fetch origin $branch` line, but then fails to run the `git diff --name-only` line.

**Comment by sunkickr** [comment]
your custom checkout step need to have fetch depth of 0 so all the commits in the PR are checked out. Here is the checkout step that the deploy action uses. Id just copy this one:

```
- name: checkout repo
      uses: actions/checkout@v4
      if: inputs.checkout == 'true'
      with:
        fetch-depth: 0  # Fetch all history
        ref: ${{ github.event.after }}
        clean: false
```
