### ISSUE TITLE
v0.7 manual trigger fails when root folder defined

### ISSUE THREAD

**Issue by AstroSucheta** [astronomer/deploy-action#91]
Astro deploy does not work on v0.7 when the root folder is defined and the pipeline is triggered manually.
The customer raised this [issue](https://astronomer.zendesk.com/agent/tickets/65491) and it has been tested internally. 

Using the following GH template 

```
name: Astronomer CI - Deployment
on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  RUN_PYTEST: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.7.1
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
          DEPLOYMENT_ID: cm28zt0ts0rs101qmtpl3jagm
        with:
          deploy-type: infer
          root-folder: astronomer-example
          force: true # without this, it fails due to our custom backend integration...
          pytest: ${{ env.RUN_PYTEST }}
          description: ${{ github.ref }}
          deploy-image: true
```
