### ISSUE TITLE
conditional binary operator expected

### ISSUE THREAD

**Issue by HongVietLE** [astronomer/deploy-action#96]
# Github Actions Workflow
```yaml
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.8.0
        with:
          deployment-id: xxxxxxxxxxxxxxxxxxxxxxxxx
          force: true
          image-name: ${{ secrets.ACR_REGISTRY }}/data_orchestration:${{ env.RELEASE_TAG }}
          root-folder: data_orchestration
          workspace: yyyyyyyyyyyyyyyyyyyyyyyyy
```

Possible linked to https://github.com/astronomer/deploy-action/issues/19

# Error
```
  Branch pushed to: refs/pull/378/merge
  From https://github.com/xxx/yyy
   * branch            refs/pull/378/merge -> FETCH_HEAD
  files changed: .github/workflows/data_orchestration.yml
  /home/runner/work/_temp/10f350da-1423-4ba4-a247-8cbc7f441241.sh: line 61: conditional binary operator expected
  Error: Process completed with exit code 2.
```
